//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeenConveyance.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicle
    {
        public int VehicleId { get; set; }
        public int CompanyId { get; set; }
        public int VehicleTypeId { get; set; }
        public string VehicleName { get; set; }
        public string RegNo { get; set; }
        public string DocumentImage { get; set; }
        public string Fuel { get; set; }
        public string Capacity { get; set; }
        public bool IsActive { get; set; }
        public string Image { get; set; }
    }
}
