//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeenConveyance.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddress
    {
        public int AddressId { get; set; }
        public string AddressType { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string HouseNo { get; set; }
        public string Landmark { get; set; }
        public string Area { get; set; }
        public string Address { get; set; }
        public int CityId { get; set; }
        public string Zipcode { get; set; }
        public string MapURL { get; set; }
    }
}
