//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeenConveyance.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBidding
    {
        public int BidId { get; set; }
        public int CompanyId { get; set; }
        public int ConsignmentId { get; set; }
        public int BidAmount { get; set; }
        public System.DateTime BidOn { get; set; }
        public Nullable<System.DateTime> EstimatedDelivery { get; set; }
        public bool IsModified { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsAssigned { get; set; }
    }
}
