//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeenConveyance.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBill
    {
        public int BillId { get; set; }
        public int UserId { get; set; }
        public int BookingId { get; set; }
        public string Desc { get; set; }
        public int Price { get; set; }
        public int TollTax { get; set; }
        public int GST { get; set; }
        public int TotalPrice { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CompanyId { get; set; }
    }
}
