//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeenConveyance.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBooking
    {
        public int BookingId { get; set; }
        public int ConsignmentId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<int> TotalPayment { get; set; }
        public string Remarks { get; set; }
        public bool IsPaid { get; set; }
        public string PaymentMode { get; set; }
        public int BidId { get; set; }
    }
}
