//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeenConveyance.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComplaint
    {
        public int ComplaintId { get; set; }
        public int UserId { get; set; }
        public int CompanyId { get; set; }
        public string Subject { get; set; }
        public string Desc { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsSolved { get; set; }
        public Nullable<System.DateTime> SolvedOn { get; set; }
        public Nullable<bool> IsReplied { get; set; }
        public string RepliedText { get; set; }
    }
}
