//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeenConveyance.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConsignment
    {
        public int ConsignmentId { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverContactNo { get; set; }
        public int ReceiverPinNo { get; set; }
        public int UserId { get; set; }
        public int SourceId { get; set; }
        public int DestinationId { get; set; }
        public string Distance { get; set; }
        public string UnitType { get; set; }
        public int UnitValue { get; set; }
        public int Budget { get; set; }
        public bool IsRefregreted { get; set; }
        public bool IsFlamable { get; set; }
        public bool IsDelicate { get; set; }
        public int MinBidValue { get; set; }
        public int MaxBidValue { get; set; }
        public System.DateTime MinTime { get; set; }
        public System.DateTime MaxTime { get; set; }
        public bool IsDelivered { get; set; }
        public bool IsActive { get; set; }
        public bool IsPaid { get; set; }
    }
}
