//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeenConveyance.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConsignment
    {
        public int ConsignmentId { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverContactNo { get; set; }
        public Nullable<int> ReceiverPinNo { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> DestinationId { get; set; }
        public string Distance { get; set; }
        public string UnitType { get; set; }
        public Nullable<int> UnitValue { get; set; }
        public Nullable<int> Budget { get; set; }
        public bool IsRefregreted { get; set; }
        public bool IsFlamable { get; set; }
        public bool IsDelicate { get; set; }
        public Nullable<int> MinBidValue { get; set; }
        public Nullable<int> MaxBidValue { get; set; }
        public string MinTime { get; set; }
        public string MaxTime { get; set; }
        public bool IsDelivered { get; set; }
        public bool IsActive { get; set; }
        public bool IsPaid { get; set; }
    }
}
