//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeenConveyance.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPriceList
    {
        public int PriceListId { get; set; }
        public string UnitName { get; set; }
        public int MinValue { get; set; }
        public int MaxValue { get; set; }
        public int PricePerUnit { get; set; }
        public int CompanyId { get; set; }
        public bool IsActive { get; set; }
    }
}
