//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeenConveyance.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransportCompany
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string Logo { get; set; }
        public string CompanyPhNo { get; set; }
        public string CompanyEmail { get; set; }
        public string Password { get; set; }
        public string AboutCompany { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonNo { get; set; }
        public string WebURL { get; set; }
        public bool IsActive { get; set; }
    }
}
